#端口号
server:
  port: 9082
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: hello-service

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:9999/eureka/