#端口号
server:
  port: 9085
    
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: xxxx-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://127.0.0.1:3306/pythondb"
    username: root
    password: wanghuan
  #redis单机配置
  redis:
    database: 0
    host: 10.204.43.23
    port: 6379
    password: 
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
    protected-mode: no
  rabbitmq:
    host: 10.204.43.23
    port: 5672
    username: admin
    password: 123456

mybatis:
  #type-aliases-package: cn.wh.shang.xxxx.mapper
  #type-handlers-package: cn.wh.shang.xxxx
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:9999/eureka/
      
#logback日志配置
logging:
  config: classpath:logback-spring.xml
  