server:
  port: 10000
  
test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin

spring:
  profiles:
    active: path-route      #使用哪个配置文件
  application:
    name: hello-gateway     #服务名
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/