spring:
  profiles: path-route            #配置文件名 和 spring.profiles.active 相对应
  cloud:
    #设置路由规则
    gateway:
      routes:
      
      - id: gateway
        uri: lb://hello-service        #代表从注册中心获取服务，且以lb(load-balance)负载均衡方式转发
        predicates:                    #断言
        - Path=/hello/**               #表示将以/hello/**开头的请求转发到uri为lb://hello-service的地址上
        - After=2019-06-20T00:00:00.789-07:00[America/Denver] #表示在该时间点之后的时间，发出的请求会被路由到uri
        filters:
        - name: Hystrix
          args: 
            name: hello-service-provider-fallback
            fallbackUri: forward:/hello-service-provider-error
        - name: Retry
          args: 
            retries: 3
            statuses: BAD_GATEWAY,BAD_REQUEST  
            
      - id: gateway-xxxx-service
        uri: lb://xxxx-service
        predicates: 
        - Path=/user/**
        - Path=/redistest/**
            
      - id: gateway-hystrix-user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        - Path=/redistest/**
        filters:
        - name: Hystrix
          args: 
            name: user-service-provider-fallback
            fallbackUri: forward:/user-service-provider-error
        - name: Retry
          args: 
            retries: 3
            statuses: BAD_GATEWAY,BAD_REQUEST  
      
      default-filters: 
       - name: Hystrix
         args:
           name: fallbackcmd
           fallbackUri: forward:/default-error
        
      discovery:
        locator:
          #表示gateway开启服务注册和发现功能,
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true
          
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 3000